{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [],
   "source": [
    "import requests\n",
    "import json\n",
    "import time\n",
    "import random"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Get BEARER_TOKEN from key.json\n",
    "with open('../../key.json') as f:\n",
    "\tkey = json.load(f)\n",
    "\tbearer_token = key['BEARER_TOKEN']"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Get random user id\n",
    "def random_id():\n",
    "\t# Get random number between 0 and 9\n",
    "\tuser_id = \"\"\n",
    "\tuser_id_length = random.randint(1,19)\n",
    "\tfor i in range(user_id_length):\n",
    "\t\tuser_id += str(random.randint(0,9))\n",
    "\treturn user_id"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Get timeline\n",
    "def get_timeline(num_tweets = 5):\n",
    "\t# Create the url\n",
    "\twhile True:\n",
    "\t\tuser_id = random_id()\n",
    "\t\turl = 'https://api.twitter.com/2/users/' + user_id + '/tweets?max_results=' + str(num_tweets)\n",
    "\t\t# Create request headers\n",
    "\t\theaders = {\n",
    "\t\t\t'authorization': 'Bearer ' + bearer_token,\n",
    "\t\t\t'user-agent': 'v2FilteredStreamPython',\n",
    "\t\t}\n",
    "\t\tresponse = requests.get(url, headers=headers).json()\n",
    "\t\ttry:\n",
    "\t\t\tif len(response['data']) == num_tweets:\n",
    "\t\t\t\tprint(\"Good user id\")\n",
    "\t\t\t\tprint(response)\n",
    "\t\t\t\tbreak\n",
    "\t\texcept:\n",
    "\t\t\tprint(\"not good id\")\n",
    "\t\t\tprint(response)\n",
    "\t\ttime.sleep(1)\n",
    "\t\n",
    "\treturn response, user_id"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "not good id\n",
      "{'errors': [{'value': '79896867081', 'detail': 'Could not find user with id: [79896867081].', 'title': 'Not Found Error', 'resource_type': 'user', 'parameter': 'id', 'resource_id': '79896867081', 'type': 'https://api.twitter.com/2/problems/resource-not-found'}]}\n",
      "not good id\n",
      "{'errors': [{'value': '49916187279', 'detail': 'Could not find user with id: [49916187279].', 'title': 'Not Found Error', 'resource_type': 'user', 'parameter': 'id', 'resource_id': '49916187279', 'type': 'https://api.twitter.com/2/problems/resource-not-found'}]}\n",
      "not good id\n",
      "{'errors': [{'value': '53420', 'detail': 'Could not find user with id: [53420].', 'title': 'Not Found Error', 'resource_type': 'user', 'parameter': 'id', 'resource_id': '53420', 'type': 'https://api.twitter.com/2/problems/resource-not-found'}]}\n",
      "not good id\n",
      "{'errors': [{'value': '042', 'detail': 'Could not find user with id: [042].', 'title': 'Not Found Error', 'resource_type': 'user', 'parameter': 'id', 'resource_id': '042', 'type': 'https://api.twitter.com/2/problems/resource-not-found'}]}\n",
      "Good user id\n",
      "{'data': [{'id': '28267584247832577', 'text': 'Alasaaaaaaan berangkat lebih pagi doong wkwkwkwkwkkkkk RT @taschameiriana: Udh 3 hari,jalanan gak bersahabat..telaatttt terusssss,'}, {'id': '27185066387972096', 'text': 'Belok kiri aja ncong sarapan dulu RT @taschameiriana: Gilaaa nih kuningan macetnyaaaa,ud keliatan gedungnya tapi (cont) http://tl.gd/87d077'}, {'id': '26882705387950080', 'text': 'Kangen niy liburan bareng loe ncoong RT @taschameiriana: Maklummmmm,akyu lg di tempat nasabahRT @valast: (cont) http://tl.gd/86qj5e'}, {'id': '26860622415138816', 'text': 'Wkwkwkwkwwkkk jgn sensi dong ncooong.. btw tachong dimana? RT @feritaldo: Hahahhahaha pasti sensiRT (cont) http://tl.gd/86pbnu'}, {'id': '26822830477807616', 'text': 'Tender alhandulillah, engagement letter  signing...  Semoga akhir bulan new site turun... Amin'}], 'meta': {'oldest_id': '26822830477807616', 'newest_id': '28267584247832577', 'result_count': 5, 'next_token': '506yuzpqzgpcu3j2p08tiwrog137nfm0af9rpy9mpi'}}\n",
      "not good id\n",
      "{'errors': [{'value': '8782574326', 'detail': 'Could not find user with id: [8782574326].', 'title': 'Not Found Error', 'resource_type': 'user', 'parameter': 'id', 'resource_id': '8782574326', 'type': 'https://api.twitter.com/2/problems/resource-not-found'}]}\n",
      "not good id\n",
      "{'errors': [{'value': '4364214', 'detail': 'Could not find user with id: [4364214].', 'title': 'Not Found Error', 'resource_type': 'user', 'parameter': 'id', 'resource_id': '4364214', 'type': 'https://api.twitter.com/2/problems/resource-not-found'}]}\n",
      "not good id\n",
      "{'errors': [{'value': '1378824', 'detail': 'Could not find user with id: [1378824].', 'title': 'Not Found Error', 'resource_type': 'user', 'parameter': 'id', 'resource_id': '1378824', 'type': 'https://api.twitter.com/2/problems/resource-not-found'}]}\n",
      "not good id\n",
      "{'errors': [{'value': '93510292657805', 'detail': 'Could not find user with id: [93510292657805].', 'title': 'Not Found Error', 'resource_type': 'user', 'parameter': 'id', 'resource_id': '93510292657805', 'type': 'https://api.twitter.com/2/problems/resource-not-found'}]}\n",
      "not good id\n",
      "{'errors': [{'value': '6675186', 'detail': 'Could not find user with id: [6675186].', 'title': 'Not Found Error', 'resource_type': 'user', 'parameter': 'id', 'resource_id': '6675186', 'type': 'https://api.twitter.com/2/problems/resource-not-found'}]}\n",
      "not good id\n",
      "{'meta': {'result_count': 0}}\n",
      "not good id\n",
      "{'errors': [{'value': '972521', 'detail': 'Could not find user with id: [972521].', 'title': 'Not Found Error', 'resource_type': 'user', 'parameter': 'id', 'resource_id': '972521', 'type': 'https://api.twitter.com/2/problems/resource-not-found'}]}\n",
      "not good id\n",
      "{'errors': [{'value': '266900364503611296', 'detail': 'Could not find user with id: [266900364503611296].', 'title': 'Not Found Error', 'resource_type': 'user', 'parameter': 'id', 'resource_id': '266900364503611296', 'type': 'https://api.twitter.com/2/problems/resource-not-found'}]}\n",
      "not good id\n",
      "{'errors': [{'value': '911039097572476', 'detail': 'Could not find user with id: [911039097572476].', 'title': 'Not Found Error', 'resource_type': 'user', 'parameter': 'id', 'resource_id': '911039097572476', 'type': 'https://api.twitter.com/2/problems/resource-not-found'}]}\n",
      "not good id\n",
      "{'errors': [{'value': '99888', 'detail': 'Could not find user with id: [99888].', 'title': 'Not Found Error', 'resource_type': 'user', 'parameter': 'id', 'resource_id': '99888', 'type': 'https://api.twitter.com/2/problems/resource-not-found'}]}\n",
      "not good id\n",
      "{'errors': [{'value': '18338524691', 'detail': 'Could not find user with id: [18338524691].', 'title': 'Not Found Error', 'resource_type': 'user', 'parameter': 'id', 'resource_id': '18338524691', 'type': 'https://api.twitter.com/2/problems/resource-not-found'}]}\n",
      "Good user id\n",
      "{'data': [{'id': '1445579405514870796', 'text': 'Nice piece featuring the amazing Dr. David Spiegel. My co-founder at https://t.co/lwNZLTey9c. #hypnosisworks. #reverihealth.  https://t.co/RIo70bFDta'}, {'id': '1433564186630664193', 'text': '@SupportRequests #0227102401 (@ :) https://t.co/OAZcUZ9N4D'}, {'id': '1433251934027255810', 'text': '@SupportRequests #0226910028 (@ -) https://t.co/sqIzpTodCU'}, {'id': '1433185966353698818', 'text': '@SupportRequests #0226879571 (@ :) https://t.co/aJuFgniEiE'}, {'id': '1432861480853065731', 'text': '@SupportRequests #0226666771 (@ .) https://t.co/Wsf4ldzYT3'}], 'meta': {'oldest_id': '1432861480853065731', 'newest_id': '1445579405514870796', 'result_count': 5, 'next_token': '7140dibdnow9c7btw3z218kj28qql5dtmb2n7n3hshxdd'}}\n",
      "not good id\n",
      "{'errors': [{'value': '547', 'detail': 'Could not find user with id: [547].', 'title': 'Not Found Error', 'resource_type': 'user', 'parameter': 'id', 'resource_id': '547', 'type': 'https://api.twitter.com/2/problems/resource-not-found'}]}\n",
      "not good id\n",
      "{'errors': [{'value': '21612849866117743', 'detail': 'Could not find user with id: [21612849866117743].', 'title': 'Not Found Error', 'resource_type': 'user', 'parameter': 'id', 'resource_id': '21612849866117743', 'type': 'https://api.twitter.com/2/problems/resource-not-found'}]}\n",
      "not good id\n",
      "{'errors': [{'value': '3720556767080589366', 'detail': 'Could not find user with id: [3720556767080589366].', 'title': 'Not Found Error', 'resource_type': 'user', 'parameter': 'id', 'resource_id': '3720556767080589366', 'type': 'https://api.twitter.com/2/problems/resource-not-found'}]}\n",
      "not good id\n",
      "{'errors': [{'value': '271649970267453', 'detail': 'Could not find user with id: [271649970267453].', 'title': 'Not Found Error', 'resource_type': 'user', 'parameter': 'id', 'resource_id': '271649970267453', 'type': 'https://api.twitter.com/2/problems/resource-not-found'}]}\n",
      "not good id\n",
      "{'errors': [{'value': '15123217285', 'detail': 'Could not find user with id: [15123217285].', 'title': 'Not Found Error', 'resource_type': 'user', 'parameter': 'id', 'resource_id': '15123217285', 'type': 'https://api.twitter.com/2/problems/resource-not-found'}]}\n",
      "not good id\n",
      "{'errors': [{'value': '8009176', 'detail': 'Could not find user with id: [8009176].', 'title': 'Not Found Error', 'resource_type': 'user', 'parameter': 'id', 'resource_id': '8009176', 'type': 'https://api.twitter.com/2/problems/resource-not-found'}]}\n",
      "not good id\n",
      "{'errors': [{'value': '3324277', 'detail': 'Could not find user with id: [3324277].', 'title': 'Not Found Error', 'resource_type': 'user', 'parameter': 'id', 'resource_id': '3324277', 'type': 'https://api.twitter.com/2/problems/resource-not-found'}]}\n",
      "not good id\n",
      "{'errors': [{'value': '623', 'detail': 'Could not find user with id: [623].', 'title': 'Not Found Error', 'resource_type': 'user', 'parameter': 'id', 'resource_id': '623', 'type': 'https://api.twitter.com/2/problems/resource-not-found'}]}\n",
      "not good id\n",
      "{'errors': [{'value': '028', 'detail': 'Could not find user with id: [028].', 'title': 'Not Found Error', 'resource_type': 'user', 'parameter': 'id', 'resource_id': '028', 'type': 'https://api.twitter.com/2/problems/resource-not-found'}]}\n",
      "not good id\n",
      "{'errors': [{'value': '6379444805', 'detail': 'Could not find user with id: [6379444805].', 'title': 'Not Found Error', 'resource_type': 'user', 'parameter': 'id', 'resource_id': '6379444805', 'type': 'https://api.twitter.com/2/problems/resource-not-found'}]}\n",
      "not good id\n",
      "{'errors': [{'value': '10599007326624', 'detail': 'Could not find user with id: [10599007326624].', 'title': 'Not Found Error', 'resource_type': 'user', 'parameter': 'id', 'resource_id': '10599007326624', 'type': 'https://api.twitter.com/2/problems/resource-not-found'}]}\n",
      "not good id\n",
      "{'errors': [{'value': '1', 'detail': 'Could not find user with id: [1].', 'title': 'Not Found Error', 'resource_type': 'user', 'parameter': 'id', 'resource_id': '1', 'type': 'https://api.twitter.com/2/problems/resource-not-found'}]}\n",
      "not good id\n",
      "{'errors': [{'value': '358246', 'detail': 'Could not find user with id: [358246].', 'title': 'Not Found Error', 'resource_type': 'user', 'parameter': 'id', 'resource_id': '358246', 'type': 'https://api.twitter.com/2/problems/resource-not-found'}]}\n",
      "not good id\n",
      "{'errors': [{'value': '5329', 'detail': 'Could not find user with id: [5329].', 'title': 'Not Found Error', 'resource_type': 'user', 'parameter': 'id', 'resource_id': '5329', 'type': 'https://api.twitter.com/2/problems/resource-not-found'}]}\n",
      "not good id\n",
      "{'errors': [{'value': '950807177061104740', 'detail': 'Could not find user with id: [950807177061104740].', 'title': 'Not Found Error', 'resource_type': 'user', 'parameter': 'id', 'resource_id': '950807177061104740', 'type': 'https://api.twitter.com/2/problems/resource-not-found'}]}\n",
      "not good id\n",
      "{'errors': [{'value': '8646556360682100', 'detail': 'Could not find user with id: [8646556360682100].', 'title': 'Not Found Error', 'resource_type': 'user', 'parameter': 'id', 'resource_id': '8646556360682100', 'type': 'https://api.twitter.com/2/problems/resource-not-found'}]}\n",
      "not good id\n",
      "{'errors': [{'value': '432400953019927817', 'detail': 'Could not find user with id: [432400953019927817].', 'title': 'Not Found Error', 'resource_type': 'user', 'parameter': 'id', 'resource_id': '432400953019927817', 'type': 'https://api.twitter.com/2/problems/resource-not-found'}]}\n",
      "not good id\n",
      "{'errors': [{'value': '30910', 'detail': 'Could not find user with id: [30910].', 'title': 'Not Found Error', 'resource_type': 'user', 'parameter': 'id', 'resource_id': '30910', 'type': 'https://api.twitter.com/2/problems/resource-not-found'}]}\n",
      "not good id\n",
      "{'meta': {'result_count': 0}}\n",
      "not good id\n",
      "{'errors': [{'value': '291459', 'detail': 'Could not find user with id: [291459].', 'title': 'Not Found Error', 'resource_type': 'user', 'parameter': 'id', 'resource_id': '291459', 'type': 'https://api.twitter.com/2/problems/resource-not-found'}]}\n",
      "not good id\n",
      "{'errors': [{'value': '786872661805216280', 'detail': 'Could not find user with id: [786872661805216280].', 'title': 'Not Found Error', 'resource_type': 'user', 'parameter': 'id', 'resource_id': '786872661805216280', 'type': 'https://api.twitter.com/2/problems/resource-not-found'}]}\n",
      "not good id\n",
      "{'errors': [{'value': '562115043705', 'detail': 'Could not find user with id: [562115043705].', 'title': 'Not Found Error', 'resource_type': 'user', 'parameter': 'id', 'resource_id': '562115043705', 'type': 'https://api.twitter.com/2/problems/resource-not-found'}]}\n",
      "not good id\n",
      "{'errors': [{'value': '960297595436', 'detail': 'Could not find user with id: [960297595436].', 'title': 'Not Found Error', 'resource_type': 'user', 'parameter': 'id', 'resource_id': '960297595436', 'type': 'https://api.twitter.com/2/problems/resource-not-found'}]}\n",
      "not good id\n",
      "{'errors': [{'resource_id': '0202731392', 'parameter': 'id', 'resource_type': 'user', 'section': 'data', 'title': 'Authorization Error', 'value': '0202731392', 'detail': 'Sorry, you are not authorized to see the user with id: [0202731392].', 'type': 'https://api.twitter.com/2/problems/not-authorized-for-resource'}]}\n",
      "not good id\n",
      "{'errors': [{'value': '9042646', 'detail': 'Could not find user with id: [9042646].', 'title': 'Not Found Error', 'resource_type': 'user', 'parameter': 'id', 'resource_id': '9042646', 'type': 'https://api.twitter.com/2/problems/resource-not-found'}]}\n",
      "Good user id\n",
      "{'data': [{'id': '1485689012077862912', 'text': '@olyalo @Spotify Congratulations Olya!'}, {'id': '1482147006596280322', 'text': '@engineering_bae Google knows best'}, {'id': '1482049165999837189', 'text': '@suedeyloh @davidfowl I had a friend who’d bring it to open book tests in college for that reason. @andykeep'}, {'id': '1479415463826186241', 'text': '@ch You’re still likely to be infectious after 48 hrs.'}, {'id': '1479407040191602688', 'text': '@notdanilu Congrats! I was diagnosed in my early 30’s and it was a breath of fresh air.'}], 'meta': {'oldest_id': '1479407040191602688', 'newest_id': '1485689012077862912', 'result_count': 5, 'next_token': '7140dibdnow9c7btw3z3q9w6d0ibfd9d3gfk13m3xogu0'}}\n",
      "not good id\n",
      "{'errors': [{'value': '643789789', 'detail': 'Could not find user with id: [643789789].', 'title': 'Not Found Error', 'resource_type': 'user', 'parameter': 'id', 'resource_id': '643789789', 'type': 'https://api.twitter.com/2/problems/resource-not-found'}]}\n",
      "not good id\n",
      "{'errors': [{'value': '70884320911000', 'detail': 'Could not find user with id: [70884320911000].', 'title': 'Not Found Error', 'resource_type': 'user', 'parameter': 'id', 'resource_id': '70884320911000', 'type': 'https://api.twitter.com/2/problems/resource-not-found'}]}\n",
      "not good id\n",
      "{'errors': [{'value': '6181063578991', 'detail': 'Could not find user with id: [6181063578991].', 'title': 'Not Found Error', 'resource_type': 'user', 'parameter': 'id', 'resource_id': '6181063578991', 'type': 'https://api.twitter.com/2/problems/resource-not-found'}]}\n",
      "not good id\n",
      "{'errors': [{'value': '08616965593140851', 'detail': 'Could not find user with id: [08616965593140851].', 'title': 'Not Found Error', 'resource_type': 'user', 'parameter': 'id', 'resource_id': '08616965593140851', 'type': 'https://api.twitter.com/2/problems/resource-not-found'}]}\n",
      "not good id\n",
      "{'errors': [{'value': '057242117868809247', 'detail': 'Could not find user with id: [057242117868809247].', 'title': 'Not Found Error', 'resource_type': 'user', 'parameter': 'id', 'resource_id': '057242117868809247', 'type': 'https://api.twitter.com/2/problems/resource-not-found'}]}\n",
      "Good user id\n",
      "{'data': [{'id': '1488543344686993408', 'text': '@Temo_Maverick كان اول فنان يمنع دخول اللب للمسرح عشان الجمهور يركز مع العمل.'}, {'id': '1488476093669650435', 'text': 'بص الغل بص الغل وماله ميجراش حاجة يا كريستيانو يعني لك الشرف انك اتعادلت مع الهليكوبتر https://t.co/X9IcbJhBiu'}, {'id': '1488464678019899395', 'text': 'من ٢٥ يناير لحد موقعة الجمل خوفت انزل. بعدها نزلت عشان الشغل. كنت بعمل ديزاينز واطبعها على تيشيرتات. فبقيت اعمل ديزاينز عن الثورة وابيعهم في الميدان. كنت بكسب اكتر من الف جنيه في الشهر. وللاسف مشاركتش وقتها في ادوار بطولة عشان الاعتقالات والبلطجة اللي كانت بتحصل. https://t.co/NbtIjY4uRE'}, {'id': '1488459131602317314', 'text': 'اعلان ضيافة جوية لجميع الجنسيات من شركة الاماراتية. نفس شروط ثريد القطرية. بالتوفيق.\\nhttps://t.co/JfPGZTej5L'}, {'id': '1488425572804042753', 'text': 'اعلان ضيافة جوية للمصريين من شركة الاتحاد. للعمل من ابوظبي، الامارات. نفس شروط ثريد القطرية بس اقل طول ١٦٥ سنتي. بالتوفيق.\\nلينك التقديم في القاهرة:\\nhttps://t.co/jvScn4nMv6 \\nلينك التقديم في الاسكندرية:\\nhttps://t.co/utY9SBoNQi'}], 'meta': {'oldest_id': '1488425572804042753', 'newest_id': '1488543344686993408', 'result_count': 5, 'next_token': '7140dibdnow9c7btw3z45dde7rdb8sqzc88cp21puxdmb'}}\n",
      "not good id\n",
      "{'errors': [{'value': '65', 'detail': 'Could not find user with id: [65].', 'title': 'Not Found Error', 'resource_type': 'user', 'parameter': 'id', 'resource_id': '65', 'type': 'https://api.twitter.com/2/problems/resource-not-found'}]}\n",
      "Good user id\n",
      "{'data': [{'id': '1478801397608943618', 'text': 'For better or worse your politics do not define you. Maybe a part of you, but are we not way more complex and nuanced than politics could ever account for? Can you stop being offended by political labeling? #politicalfact #truth'}, {'id': '1419736523478487041', 'text': 'RT @jaesofamous: This is the best explanation of the Covid Vaccine I’ve ever heard. https://t.co/RAyOQT7WZv'}, {'id': '1417141957764075526', 'text': 'Do you remember when you joined Twitter? I do! #MyTwitterAnniversary https://t.co/AwtHBzxKt1'}, {'id': '1385287887659298818', 'text': 'RT @pattonoswalt: Please please watch this https://t.co/PHrxzlDuhw'}, {'id': '1378726426040365061', 'text': '@smashingmag Currently working two jobs, 5 days a week teaching, 2 days a week retail, 7 days a week underpaid.'}], 'meta': {'oldest_id': '1378726426040365061', 'newest_id': '1478801397608943618', 'result_count': 5, 'next_token': '7140dibdnow9c7btw3w3ybr5lrvgal5jhe9y4rgsabkfl'}}\n",
      "not good id\n",
      "{'errors': [{'value': '36770685311', 'detail': 'Could not find user with id: [36770685311].', 'title': 'Not Found Error', 'resource_type': 'user', 'parameter': 'id', 'resource_id': '36770685311', 'type': 'https://api.twitter.com/2/problems/resource-not-found'}]}\n",
      "not good id\n",
      "{'errors': [{'value': '7338', 'detail': 'Could not find user with id: [7338].', 'title': 'Not Found Error', 'resource_type': 'user', 'parameter': 'id', 'resource_id': '7338', 'type': 'https://api.twitter.com/2/problems/resource-not-found'}]}\n",
      "not good id\n",
      "{'errors': [{'value': '65686', 'detail': 'Could not find user with id: [65686].', 'title': 'Not Found Error', 'resource_type': 'user', 'parameter': 'id', 'resource_id': '65686', 'type': 'https://api.twitter.com/2/problems/resource-not-found'}]}\n",
      "not good id\n",
      "{'errors': [{'value': '7300758772', 'detail': 'Could not find user with id: [7300758772].', 'title': 'Not Found Error', 'resource_type': 'user', 'parameter': 'id', 'resource_id': '7300758772', 'type': 'https://api.twitter.com/2/problems/resource-not-found'}]}\n",
      "not good id\n",
      "{'meta': {'result_count': 0}}\n",
      "not good id\n",
      "{'errors': [{'value': '486192173457799', 'detail': 'Could not find user with id: [486192173457799].', 'title': 'Not Found Error', 'resource_type': 'user', 'parameter': 'id', 'resource_id': '486192173457799', 'type': 'https://api.twitter.com/2/problems/resource-not-found'}]}\n",
      "not good id\n",
      "{'errors': [{'value': '232814', 'detail': 'Could not find user with id: [232814].', 'title': 'Not Found Error', 'resource_type': 'user', 'parameter': 'id', 'resource_id': '232814', 'type': 'https://api.twitter.com/2/problems/resource-not-found'}]}\n",
      "not good id\n",
      "{'errors': [{'value': '8163269254784', 'detail': 'Could not find user with id: [8163269254784].', 'title': 'Not Found Error', 'resource_type': 'user', 'parameter': 'id', 'resource_id': '8163269254784', 'type': 'https://api.twitter.com/2/problems/resource-not-found'}]}\n",
      "not good id\n",
      "{'errors': [{'value': '6226066262549561', 'detail': 'Could not find user with id: [6226066262549561].', 'title': 'Not Found Error', 'resource_type': 'user', 'parameter': 'id', 'resource_id': '6226066262549561', 'type': 'https://api.twitter.com/2/problems/resource-not-found'}]}\n",
      "not good id\n",
      "{'errors': [{'value': '4252622493212553386', 'detail': 'Could not find user with id: [4252622493212553386].', 'title': 'Not Found Error', 'resource_type': 'user', 'parameter': 'id', 'resource_id': '4252622493212553386', 'type': 'https://api.twitter.com/2/problems/resource-not-found'}]}\n",
      "not good id\n",
      "{'errors': [{'value': '22460600677555875', 'detail': 'Could not find user with id: [22460600677555875].', 'title': 'Not Found Error', 'resource_type': 'user', 'parameter': 'id', 'resource_id': '22460600677555875', 'type': 'https://api.twitter.com/2/problems/resource-not-found'}]}\n",
      "not good id\n",
      "{'errors': [{'value': '4601701486422', 'detail': 'Could not find user with id: [4601701486422].', 'title': 'Not Found Error', 'resource_type': 'user', 'parameter': 'id', 'resource_id': '4601701486422', 'type': 'https://api.twitter.com/2/problems/resource-not-found'}]}\n",
      "not good id\n",
      "{'errors': [{'value': '0401734643', 'detail': 'Could not find user with id: [0401734643].', 'title': 'Not Found Error', 'resource_type': 'user', 'parameter': 'id', 'resource_id': '0401734643', 'type': 'https://api.twitter.com/2/problems/resource-not-found'}]}\n",
      "not good id\n",
      "{'errors': [{'value': '1622589590330187', 'detail': 'Could not find user with id: [1622589590330187].', 'title': 'Not Found Error', 'resource_type': 'user', 'parameter': 'id', 'resource_id': '1622589590330187', 'type': 'https://api.twitter.com/2/problems/resource-not-found'}]}\n",
      "not good id\n",
      "{'errors': [{'value': '4232969461', 'detail': 'Could not find user with id: [4232969461].', 'title': 'Not Found Error', 'resource_type': 'user', 'parameter': 'id', 'resource_id': '4232969461', 'type': 'https://api.twitter.com/2/problems/resource-not-found'}]}\n",
      "Good user id\n",
      "{'data': [{'id': '1485712403828404224', 'text': '@Darkmage54 @AnkerOfficial Yes, log in with the same shared credentials on both phones.'}, {'id': '1484266817509986305', 'text': \"@WyzeCam I'm a Cam Plus legacy person detection member and I still can't subscribe to Cam Plus Lite. Why are you prioritizing free users over subscribers to roll out this program?\"}, {'id': '1480949756255883267', 'text': \"@NiklasQuarfot @SahilBloom I've definitely got more interest than skill in everything that I do.\"}, {'id': '1480948756308631553', 'text': 'Fun time using @BuildZoom for the second time. Now I sound like a broken record. https://t.co/usg2Ek8NlW'}, {'id': '1467974393460510720', 'text': \"@launchbar @launchbar any ideas? I've been using Launchbar for over a decade but now the laptop is unusable when it's loaded. Monterey 12.0.1 on an 2020 i5 MacBook Pro. You don't seem to have real support.\"}], 'meta': {'oldest_id': '1467974393460510720', 'newest_id': '1485712403828404224', 'result_count': 5, 'next_token': '7140dibdnow9c7btw3z3b02ae16k2ajzi5q1qdtmnrhv4'}}\n",
      "not good id\n",
      "{'errors': [{'value': '79647623977682028', 'detail': 'Could not find user with id: [79647623977682028].', 'title': 'Not Found Error', 'resource_type': 'user', 'parameter': 'id', 'resource_id': '79647623977682028', 'type': 'https://api.twitter.com/2/problems/resource-not-found'}]}\n",
      "not good id\n",
      "{'errors': [{'value': '6', 'detail': 'Could not find user with id: [6].', 'title': 'Not Found Error', 'resource_type': 'user', 'parameter': 'id', 'resource_id': '6', 'type': 'https://api.twitter.com/2/problems/resource-not-found'}]}\n",
      "not good id\n",
      "{'errors': [{'parameter': 'id', 'resource_id': '250068299', 'value': '250068299', 'detail': 'User has been suspended: [250068299].', 'title': 'Forbidden', 'resource_type': 'user', 'type': 'https://api.twitter.com/2/problems/resource-not-found'}]}\n",
      "not good id\n",
      "{'errors': [{'value': '9', 'detail': 'Could not find user with id: [9].', 'title': 'Not Found Error', 'resource_type': 'user', 'parameter': 'id', 'resource_id': '9', 'type': 'https://api.twitter.com/2/problems/resource-not-found'}]}\n",
      "not good id\n",
      "{'errors': [{'value': '994308', 'detail': 'Could not find user with id: [994308].', 'title': 'Not Found Error', 'resource_type': 'user', 'parameter': 'id', 'resource_id': '994308', 'type': 'https://api.twitter.com/2/problems/resource-not-found'}]}\n",
      "Good user id\n",
      "{'data': [{'id': '214325108846772224', 'text': '@tokiusagixxx \\u3000え、あ…あぁ、わかった…戻ってきたら伝えておくわ…\\u3000気を付けてぇな。（手を横にふり\\u3000'}, {'id': '214322038385545216', 'text': '@tokiusagixxx \\u3000な……あぴこさんがそうなら僕は止めへんよ…（止めようと少し前にでるも、すぐに足止め下俯き\\u3000'}, {'id': '214316926531407872', 'text': '@tokiusagixxx \\u3000待て待て待て、刺すなら僕ごと刺してもかまわへん！！\\u3000やから、死ぬのだけは止めてくれへんか！？人が死ぬのは…見たくないんや。\\u3000'}, {'id': '214314903429853184', 'text': 'あぁあああぁああかん！来てもうた！！！\\u3000'}, {'id': '214314830755147777', 'text': '@tokiusagixxx \\u3000な、そうやった、で、でも、そうすると止めてくれるのあぴこさんしかおらへんのや！！！\\u3000僕かて全く力あらへんし…（慌てて相手の手首つかみ\\u3000'}], 'meta': {'oldest_id': '214314830755147777', 'newest_id': '214325108846772224', 'result_count': 5, 'next_token': 'zldjwdz3w6sba13n5rmpe5l3w8qlyoq9wjh5kxhqiwn'}}\n",
      "not good id\n",
      "{'errors': [{'value': '64003984329389', 'detail': 'Could not find user with id: [64003984329389].', 'title': 'Not Found Error', 'resource_type': 'user', 'parameter': 'id', 'resource_id': '64003984329389', 'type': 'https://api.twitter.com/2/problems/resource-not-found'}]}\n",
      "not good id\n",
      "{'errors': [{'value': '1420', 'detail': 'Could not find user with id: [1420].', 'title': 'Not Found Error', 'resource_type': 'user', 'parameter': 'id', 'resource_id': '1420', 'type': 'https://api.twitter.com/2/problems/resource-not-found'}]}\n",
      "not good id\n",
      "{'errors': [{'value': '6', 'detail': 'Could not find user with id: [6].', 'title': 'Not Found Error', 'resource_type': 'user', 'parameter': 'id', 'resource_id': '6', 'type': 'https://api.twitter.com/2/problems/resource-not-found'}]}\n",
      "not good id\n",
      "{'errors': [{'value': '81603822185', 'detail': 'Could not find user with id: [81603822185].', 'title': 'Not Found Error', 'resource_type': 'user', 'parameter': 'id', 'resource_id': '81603822185', 'type': 'https://api.twitter.com/2/problems/resource-not-found'}]}\n",
      "not good id\n",
      "{'errors': [{'value': '1581200077533', 'detail': 'Could not find user with id: [1581200077533].', 'title': 'Not Found Error', 'resource_type': 'user', 'parameter': 'id', 'resource_id': '1581200077533', 'type': 'https://api.twitter.com/2/problems/resource-not-found'}]}\n",
      "not good id\n",
      "{'errors': [{'value': '09693327', 'detail': 'Could not find user with id: [09693327].', 'title': 'Not Found Error', 'resource_type': 'user', 'parameter': 'id', 'resource_id': '09693327', 'type': 'https://api.twitter.com/2/problems/resource-not-found'}]}\n",
      "not good id\n",
      "{'errors': [{'value': '7129140', 'detail': 'Could not find user with id: [7129140].', 'title': 'Not Found Error', 'resource_type': 'user', 'parameter': 'id', 'resource_id': '7129140', 'type': 'https://api.twitter.com/2/problems/resource-not-found'}]}\n",
      "not good id\n",
      "{'errors': [{'value': '21226404772585', 'detail': 'Could not find user with id: [21226404772585].', 'title': 'Not Found Error', 'resource_type': 'user', 'parameter': 'id', 'resource_id': '21226404772585', 'type': 'https://api.twitter.com/2/problems/resource-not-found'}]}\n",
      "not good id\n",
      "{'errors': [{'value': '84427958121', 'detail': 'Could not find user with id: [84427958121].', 'title': 'Not Found Error', 'resource_type': 'user', 'parameter': 'id', 'resource_id': '84427958121', 'type': 'https://api.twitter.com/2/problems/resource-not-found'}]}\n",
      "not good id\n",
      "{'errors': [{'parameter': 'id', 'resource_id': '217577844', 'value': '217577844', 'detail': 'User has been suspended: [217577844].', 'title': 'Forbidden', 'resource_type': 'user', 'type': 'https://api.twitter.com/2/problems/resource-not-found'}]}\n",
      "not good id\n",
      "{'errors': [{'value': '46083607906935869', 'detail': 'Could not find user with id: [46083607906935869].', 'title': 'Not Found Error', 'resource_type': 'user', 'parameter': 'id', 'resource_id': '46083607906935869', 'type': 'https://api.twitter.com/2/problems/resource-not-found'}]}\n",
      "not good id\n",
      "{'errors': [{'value': '07192659813', 'detail': 'Could not find user with id: [07192659813].', 'title': 'Not Found Error', 'resource_type': 'user', 'parameter': 'id', 'resource_id': '07192659813', 'type': 'https://api.twitter.com/2/problems/resource-not-found'}]}\n",
      "not good id\n",
      "{'errors': [{'value': '826682', 'detail': 'Could not find user with id: [826682].', 'title': 'Not Found Error', 'resource_type': 'user', 'parameter': 'id', 'resource_id': '826682', 'type': 'https://api.twitter.com/2/problems/resource-not-found'}]}\n",
      "not good id\n",
      "{'errors': [{'value': '7897448064216616899', 'detail': 'Could not find user with id: [7897448064216616899].', 'title': 'Not Found Error', 'resource_type': 'user', 'parameter': 'id', 'resource_id': '7897448064216616899', 'type': 'https://api.twitter.com/2/problems/resource-not-found'}]}\n",
      "not good id\n",
      "{'errors': [{'value': '34912625605', 'detail': 'Could not find user with id: [34912625605].', 'title': 'Not Found Error', 'resource_type': 'user', 'parameter': 'id', 'resource_id': '34912625605', 'type': 'https://api.twitter.com/2/problems/resource-not-found'}]}\n",
      "not good id\n",
      "{'errors': [{'value': '73', 'detail': 'Could not find user with id: [73].', 'title': 'Not Found Error', 'resource_type': 'user', 'parameter': 'id', 'resource_id': '73', 'type': 'https://api.twitter.com/2/problems/resource-not-found'}]}\n",
      "not good id\n",
      "{'errors': [{'value': '8817440704271', 'detail': 'Could not find user with id: [8817440704271].', 'title': 'Not Found Error', 'resource_type': 'user', 'parameter': 'id', 'resource_id': '8817440704271', 'type': 'https://api.twitter.com/2/problems/resource-not-found'}]}\n",
      "not good id\n",
      "{'errors': [{'value': '86525035848', 'detail': 'Could not find user with id: [86525035848].', 'title': 'Not Found Error', 'resource_type': 'user', 'parameter': 'id', 'resource_id': '86525035848', 'type': 'https://api.twitter.com/2/problems/resource-not-found'}]}\n",
      "not good id\n",
      "{'errors': [{'value': '7886083', 'detail': 'Could not find user with id: [7886083].', 'title': 'Not Found Error', 'resource_type': 'user', 'parameter': 'id', 'resource_id': '7886083', 'type': 'https://api.twitter.com/2/problems/resource-not-found'}]}\n",
      "not good id\n",
      "{'errors': [{'parameter': 'id', 'resource_id': '6226', 'value': '6226', 'detail': 'User has been suspended: [6226].', 'title': 'Forbidden', 'resource_type': 'user', 'type': 'https://api.twitter.com/2/problems/resource-not-found'}]}\n",
      "not good id\n",
      "{'errors': [{'value': '10131417032990', 'detail': 'Could not find user with id: [10131417032990].', 'title': 'Not Found Error', 'resource_type': 'user', 'parameter': 'id', 'resource_id': '10131417032990', 'type': 'https://api.twitter.com/2/problems/resource-not-found'}]}\n",
      "Good user id\n",
      "{'data': [{'id': '1486125600347602945', 'text': 'this thread is sublime ⭐️ https://t.co/ioVoz6ETH6'}, {'id': '1478151976646963202', 'text': '@NASA @TheExpanseWR @NASA_SLS sa sa, bosmang 🙌🏼💯'}, {'id': '1475595016277880833', 'text': '@100soft gotta give a nod to https://t.co/OIgegBCZ3t'}, {'id': '1472011492220289024', 'text': '‘liberal bias’ lol https://t.co/3NvXHAxZ9H'}, {'id': '1467888340082909189', 'text': 'wow- for once, i totally agree with this 🤡 https://t.co/pMoOMBDiZh'}], 'meta': {'oldest_id': '1467888340082909189', 'newest_id': '1486125600347602945', 'result_count': 5, 'next_token': '7140dibdnow9c7btw3z3b01zn5a76k8ncfvxjrlzrt5ix'}}\n",
      "not good id\n",
      "{'errors': [{'value': '6997183371350', 'detail': 'Could not find user with id: [6997183371350].', 'title': 'Not Found Error', 'resource_type': 'user', 'parameter': 'id', 'resource_id': '6997183371350', 'type': 'https://api.twitter.com/2/problems/resource-not-found'}]}\n",
      "not good id\n",
      "{'errors': [{'value': '429336432840', 'detail': 'Could not find user with id: [429336432840].', 'title': 'Not Found Error', 'resource_type': 'user', 'parameter': 'id', 'resource_id': '429336432840', 'type': 'https://api.twitter.com/2/problems/resource-not-found'}]}\n",
      "not good id\n",
      "{'errors': [{'value': '40', 'detail': 'Could not find user with id: [40].', 'title': 'Not Found Error', 'resource_type': 'user', 'parameter': 'id', 'resource_id': '40', 'type': 'https://api.twitter.com/2/problems/resource-not-found'}]}\n",
      "not good id\n",
      "{'errors': [{'value': '27', 'detail': 'Could not find user with id: [27].', 'title': 'Not Found Error', 'resource_type': 'user', 'parameter': 'id', 'resource_id': '27', 'type': 'https://api.twitter.com/2/problems/resource-not-found'}]}\n",
      "not good id\n",
      "{'errors': [{'value': '241719', 'detail': 'Could not find user with id: [241719].', 'title': 'Not Found Error', 'resource_type': 'user', 'parameter': 'id', 'resource_id': '241719', 'type': 'https://api.twitter.com/2/problems/resource-not-found'}]}\n",
      "not good id\n",
      "{'errors': [{'value': '002093185863391283', 'detail': 'Could not find user with id: [002093185863391283].', 'title': 'Not Found Error', 'resource_type': 'user', 'parameter': 'id', 'resource_id': '002093185863391283', 'type': 'https://api.twitter.com/2/problems/resource-not-found'}]}\n",
      "not good id\n",
      "{'errors': [{'value': '947258762', 'detail': 'Could not find user with id: [947258762].', 'title': 'Not Found Error', 'resource_type': 'user', 'parameter': 'id', 'resource_id': '947258762', 'type': 'https://api.twitter.com/2/problems/resource-not-found'}]}\n",
      "not good id\n",
      "{'errors': [{'value': '89176126051', 'detail': 'Could not find user with id: [89176126051].', 'title': 'Not Found Error', 'resource_type': 'user', 'parameter': 'id', 'resource_id': '89176126051', 'type': 'https://api.twitter.com/2/problems/resource-not-found'}]}\n",
      "not good id\n",
      "{'errors': [{'value': '67901741', 'detail': 'Could not find user with id: [67901741].', 'title': 'Not Found Error', 'resource_type': 'user', 'parameter': 'id', 'resource_id': '67901741', 'type': 'https://api.twitter.com/2/problems/resource-not-found'}]}\n",
      "not good id\n",
      "{'errors': [{'value': '36', 'detail': 'Could not find user with id: [36].', 'title': 'Not Found Error', 'resource_type': 'user', 'parameter': 'id', 'resource_id': '36', 'type': 'https://api.twitter.com/2/problems/resource-not-found'}]}\n",
      "not good id\n",
      "{'errors': [{'value': '69050', 'detail': 'Could not find user with id: [69050].', 'title': 'Not Found Error', 'resource_type': 'user', 'parameter': 'id', 'resource_id': '69050', 'type': 'https://api.twitter.com/2/problems/resource-not-found'}]}\n",
      "not good id\n",
      "{'errors': [{'value': '05125', 'detail': 'Could not find user with id: [05125].', 'title': 'Not Found Error', 'resource_type': 'user', 'parameter': 'id', 'resource_id': '05125', 'type': 'https://api.twitter.com/2/problems/resource-not-found'}]}\n",
      "not good id\n",
      "{'errors': [{'value': '1982952580', 'detail': 'Could not find user with id: [1982952580].', 'title': 'Not Found Error', 'resource_type': 'user', 'parameter': 'id', 'resource_id': '1982952580', 'type': 'https://api.twitter.com/2/problems/resource-not-found'}]}\n",
      "not good id\n",
      "{'errors': [{'value': '15151937293', 'detail': 'Could not find user with id: [15151937293].', 'title': 'Not Found Error', 'resource_type': 'user', 'parameter': 'id', 'resource_id': '15151937293', 'type': 'https://api.twitter.com/2/problems/resource-not-found'}]}\n",
      "not good id\n",
      "{'meta': {'result_count': 0}}\n",
      "not good id\n",
      "{'errors': [{'value': '1928420012909740249', 'detail': 'Could not find user with id: [1928420012909740249].', 'title': 'Not Found Error', 'resource_type': 'user', 'parameter': 'id', 'resource_id': '1928420012909740249', 'type': 'https://api.twitter.com/2/problems/resource-not-found'}]}\n",
      "not good id\n",
      "{'errors': [{'value': '108156', 'detail': 'Could not find user with id: [108156].', 'title': 'Not Found Error', 'resource_type': 'user', 'parameter': 'id', 'resource_id': '108156', 'type': 'https://api.twitter.com/2/problems/resource-not-found'}]}\n",
      "not good id\n",
      "{'errors': [{'value': '51033365884', 'detail': 'Could not find user with id: [51033365884].', 'title': 'Not Found Error', 'resource_type': 'user', 'parameter': 'id', 'resource_id': '51033365884', 'type': 'https://api.twitter.com/2/problems/resource-not-found'}]}\n",
      "not good id\n",
      "{'errors': [{'value': '653539200411294796', 'detail': 'Could not find user with id: [653539200411294796].', 'title': 'Not Found Error', 'resource_type': 'user', 'parameter': 'id', 'resource_id': '653539200411294796', 'type': 'https://api.twitter.com/2/problems/resource-not-found'}]}\n",
      "not good id\n",
      "{'errors': [{'value': '5', 'detail': 'Could not find user with id: [5].', 'title': 'Not Found Error', 'resource_type': 'user', 'parameter': 'id', 'resource_id': '5', 'type': 'https://api.twitter.com/2/problems/resource-not-found'}]}\n",
      "not good id\n",
      "{'errors': [{'value': '128455799429166482', 'detail': 'Could not find user with id: [128455799429166482].', 'title': 'Not Found Error', 'resource_type': 'user', 'parameter': 'id', 'resource_id': '128455799429166482', 'type': 'https://api.twitter.com/2/problems/resource-not-found'}]}\n",
      "not good id\n",
      "{'errors': [{'value': '093', 'detail': 'Could not find user with id: [093].', 'title': 'Not Found Error', 'resource_type': 'user', 'parameter': 'id', 'resource_id': '093', 'type': 'https://api.twitter.com/2/problems/resource-not-found'}]}\n",
      "not good id\n",
      "{'errors': [{'value': '103096419397', 'detail': 'Could not find user with id: [103096419397].', 'title': 'Not Found Error', 'resource_type': 'user', 'parameter': 'id', 'resource_id': '103096419397', 'type': 'https://api.twitter.com/2/problems/resource-not-found'}]}\n",
      "not good id\n",
      "{'errors': [{'value': '13615431049430', 'detail': 'Could not find user with id: [13615431049430].', 'title': 'Not Found Error', 'resource_type': 'user', 'parameter': 'id', 'resource_id': '13615431049430', 'type': 'https://api.twitter.com/2/problems/resource-not-found'}]}\n",
      "not good id\n",
      "{'meta': {'result_count': 0}}\n",
      "not good id\n",
      "{'errors': [{'value': '4582366617427', 'detail': 'Could not find user with id: [4582366617427].', 'title': 'Not Found Error', 'resource_type': 'user', 'parameter': 'id', 'resource_id': '4582366617427', 'type': 'https://api.twitter.com/2/problems/resource-not-found'}]}\n",
      "not good id\n",
      "{'errors': [{'value': '85929551600046', 'detail': 'Could not find user with id: [85929551600046].', 'title': 'Not Found Error', 'resource_type': 'user', 'parameter': 'id', 'resource_id': '85929551600046', 'type': 'https://api.twitter.com/2/problems/resource-not-found'}]}\n",
      "not good id\n",
      "{'errors': [{'value': '00210698665356996', 'detail': 'Could not find user with id: [00210698665356996].', 'title': 'Not Found Error', 'resource_type': 'user', 'parameter': 'id', 'resource_id': '00210698665356996', 'type': 'https://api.twitter.com/2/problems/resource-not-found'}]}\n",
      "Good user id\n",
      "{'data': [{'id': '1466653997670957057', 'text': '@Gjeebs Hahahha, this is the best twitter post today.'}, {'id': '1267533147564118016', 'text': 'https://t.co/kLLxL5xWsb'}, {'id': '1246152638233628673', 'text': '#CASCADIA ??'}, {'id': '1241264841274175490', 'text': 'RIP Kenny Rogers.  https://t.co/5iJ4e9SmsV'}, {'id': '1241028134306058240', 'text': '@elonmusk you have downplayed the seriousness of Covad-19, you kept your factories open as essential business during the crisis, can we count on you? https://t.co/sV0zeDDArf'}], 'meta': {'oldest_id': '1241028134306058240', 'newest_id': '1466653997670957057', 'result_count': 5, 'next_token': '7140dibdnow9c7btw3t2wjwy8345skken566ys4f7dyr4'}}\n",
      "not good id\n",
      "{'errors': [{'value': '68198247896622336', 'detail': 'Could not find user with id: [68198247896622336].', 'title': 'Not Found Error', 'resource_type': 'user', 'parameter': 'id', 'resource_id': '68198247896622336', 'type': 'https://api.twitter.com/2/problems/resource-not-found'}]}\n",
      "not good id\n",
      "{'errors': [{'value': '7', 'detail': 'Could not find user with id: [7].', 'title': 'Not Found Error', 'resource_type': 'user', 'parameter': 'id', 'resource_id': '7', 'type': 'https://api.twitter.com/2/problems/resource-not-found'}]}\n",
      "not good id\n",
      "{'errors': [{'value': '678637055249907', 'detail': 'Could not find user with id: [678637055249907].', 'title': 'Not Found Error', 'resource_type': 'user', 'parameter': 'id', 'resource_id': '678637055249907', 'type': 'https://api.twitter.com/2/problems/resource-not-found'}]}\n",
      "not good id\n",
      "{'errors': [{'value': '1595', 'detail': 'Could not find user with id: [1595].', 'title': 'Not Found Error', 'resource_type': 'user', 'parameter': 'id', 'resource_id': '1595', 'type': 'https://api.twitter.com/2/problems/resource-not-found'}]}\n",
      "Good user id\n",
      "{'data': [{'id': '378675940261261312', 'text': 'I wish the twitter team the best of luck and trust that they will be successful in continuing to develop this important communication tool.'}, {'id': '322174032365629441', 'text': 'Today at 4 days old Océane touched the wind for the first time. Held her tiny fingers up and touched it.'}, {'id': '320657033986727936', 'text': 'afternoon @ 12:58pm.'}, {'id': '320657025539375106', 'text': 'Cheeks stained with glorious tears of joy and absolute humility I celebrate the birth of my daughter Oceane Donnie Marie-Louise Poncin G ...'}, {'id': '58686168044281856', 'text': 'Delphine read the article aloud as I drove up hwy 1. Quite a welcome home!'}], 'meta': {'oldest_id': '58686168044281856', 'newest_id': '378675940261261312', 'result_count': 5, 'next_token': '506yuzpqzgpcu3j2q9tw7mvfk7q3fqd2t7ma6hzvw6'}}\n",
      "not good id\n",
      "{'errors': [{'value': '122326923251866955', 'detail': 'Could not find user with id: [122326923251866955].', 'title': 'Not Found Error', 'resource_type': 'user', 'parameter': 'id', 'resource_id': '122326923251866955', 'type': 'https://api.twitter.com/2/problems/resource-not-found'}]}\n",
      "not good id\n",
      "{'errors': [{'value': '04', 'detail': 'Could not find user with id: [04].', 'title': 'Not Found Error', 'resource_type': 'user', 'parameter': 'id', 'resource_id': '04', 'type': 'https://api.twitter.com/2/problems/resource-not-found'}]}\n",
      "Good user id\n",
      "{'data': [{'id': '1471383475156574212', 'text': 'RT @OPBR_official: ／\\n#ジャンプフェスタ2022\\nワンピースゲームスペシャルステージ\\n生配信決定！\\n＼\\n\\nゲストは、#ヤマト 役 #早見沙織 さん！\\n\\n12/18(土) 12:30～ 視聴↓\\nhttps://t.co/I9XpWSaFGN\\n\\nさらに！#バウン…'}, {'id': '1430513375172251654', 'text': '#ONEPIECE_BR診断 の結果は、、、\\nチャレンジ精神旺盛なアタッカータイプの\\n怪物強化 #トニートニー・チョッパー \\n\\n #ワンピースバウンティラッシュ\\n #バウンティラッシュ\\n #ONEPIECE\\n@OPBR_official \\n診断は下記のリンクからスタート https://t.co/G25t9gPxtc'}, {'id': '1430510870627557377', 'text': 'RT @OPBR_official: 【サカズキPV公開！RTキャンペーン】\\n近日！海軍本部／元帥 赤犬 【サカズキ】参戦！\\n9/1 23:59までにこのツイートが10,000RT達成で虹のダイヤ20個を全員にプレゼント！\\n#バウンティラッシュ\\n#ONEPIECE https:…'}, {'id': '1332371680623276034', 'text': 'I love u https://t.co/lnRF7M4eQc'}, {'id': '1332371613879324672', 'text': '@JLo I love u'}], 'meta': {'oldest_id': '1332371613879324672', 'newest_id': '1471383475156574212', 'result_count': 5, 'next_token': '7140dibdnow9c7btw3w29chu3enpx2gd13ksdins2nzua'}}\n",
      "not good id\n",
      "{'meta': {'result_count': 0}}\n",
      "not good id\n",
      "{'errors': [{'value': '5473389289408102956', 'detail': 'Could not find user with id: [5473389289408102956].', 'title': 'Not Found Error', 'resource_type': 'user', 'parameter': 'id', 'resource_id': '5473389289408102956', 'type': 'https://api.twitter.com/2/problems/resource-not-found'}]}\n",
      "not good id\n",
      "{'errors': [{'value': '8568', 'detail': 'Could not find user with id: [8568].', 'title': 'Not Found Error', 'resource_type': 'user', 'parameter': 'id', 'resource_id': '8568', 'type': 'https://api.twitter.com/2/problems/resource-not-found'}]}\n",
      "not good id\n",
      "{'errors': [{'value': '654871714137451', 'detail': 'Could not find user with id: [654871714137451].', 'title': 'Not Found Error', 'resource_type': 'user', 'parameter': 'id', 'resource_id': '654871714137451', 'type': 'https://api.twitter.com/2/problems/resource-not-found'}]}\n",
      "not good id\n",
      "{'errors': [{'value': '9278929', 'detail': 'Could not find user with id: [9278929].', 'title': 'Not Found Error', 'resource_type': 'user', 'parameter': 'id', 'resource_id': '9278929', 'type': 'https://api.twitter.com/2/problems/resource-not-found'}]}\n",
      "Good user id\n",
      "{'data': [{'id': '98310641923801088', 'text': 'Stay at home mam makes $374/hour work from home jobs. read it now at http://t.co/IP5iNeb'}, {'id': '97978323015184385', 'text': 'check this out! I made almost $550 today so far http://t.co/YtcNuik'}, {'id': '97412917493895168', 'text': 'check this out! I made $380 today so far http://t.co/Uo6iqd8'}, {'id': '97126590093332480', 'text': 'Stay at home moms makes $357/hour online. check it out! http://t.co/CjgrRTN'}, {'id': '12076401670754304', 'text': 'http://goo.gl/FLqa4'}], 'meta': {'oldest_id': '12076401670754304', 'newest_id': '98310641923801088', 'result_count': 5, 'next_token': '506yuzpqzgpcu3j2okumaaksswz9nv8ia6zkg1obas'}}\n",
      "not good id\n",
      "{'errors': [{'value': '8699198764', 'detail': 'Could not find user with id: [8699198764].', 'title': 'Not Found Error', 'resource_type': 'user', 'parameter': 'id', 'resource_id': '8699198764', 'type': 'https://api.twitter.com/2/problems/resource-not-found'}]}\n",
      "not good id\n",
      "{'errors': [{'value': '6161770', 'detail': 'Could not find user with id: [6161770].', 'title': 'Not Found Error', 'resource_type': 'user', 'parameter': 'id', 'resource_id': '6161770', 'type': 'https://api.twitter.com/2/problems/resource-not-found'}]}\n",
      "not good id\n",
      "{'errors': [{'value': '918471910847050', 'detail': 'Could not find user with id: [918471910847050].', 'title': 'Not Found Error', 'resource_type': 'user', 'parameter': 'id', 'resource_id': '918471910847050', 'type': 'https://api.twitter.com/2/problems/resource-not-found'}]}\n",
      "not good id\n",
      "{'errors': [{'value': '1234211421', 'detail': 'Could not find user with id: [1234211421].', 'title': 'Not Found Error', 'resource_type': 'user', 'parameter': 'id', 'resource_id': '1234211421', 'type': 'https://api.twitter.com/2/problems/resource-not-found'}]}\n",
      "not good id\n",
      "{'errors': [{'value': '05398928672793958', 'detail': 'Could not find user with id: [05398928672793958].', 'title': 'Not Found Error', 'resource_type': 'user', 'parameter': 'id', 'resource_id': '05398928672793958', 'type': 'https://api.twitter.com/2/problems/resource-not-found'}]}\n",
      "not good id\n",
      "{'errors': [{'value': '06302695', 'detail': 'Could not find user with id: [06302695].', 'title': 'Not Found Error', 'resource_type': 'user', 'parameter': 'id', 'resource_id': '06302695', 'type': 'https://api.twitter.com/2/problems/resource-not-found'}]}\n",
      "not good id\n",
      "{'errors': [{'value': '623638049669', 'detail': 'Could not find user with id: [623638049669].', 'title': 'Not Found Error', 'resource_type': 'user', 'parameter': 'id', 'resource_id': '623638049669', 'type': 'https://api.twitter.com/2/problems/resource-not-found'}]}\n",
      "not good id\n",
      "{'errors': [{'value': '5239201358084575006', 'detail': 'Could not find user with id: [5239201358084575006].', 'title': 'Not Found Error', 'resource_type': 'user', 'parameter': 'id', 'resource_id': '5239201358084575006', 'type': 'https://api.twitter.com/2/problems/resource-not-found'}]}\n",
      "not good id\n",
      "{'meta': {'result_count': 0}}\n",
      "Good user id\n",
      "{'data': [{'id': '1487110905234034695', 'text': 'Wordle 223 2/6\\n\\n🟨🟩⬜⬜🟩\\n🟩🟩🟩🟩🟩 I’m new. Is this how you do it?'}, {'id': '1478805840354185217', 'text': \"@jamesjoaquin @taikacoffee @obviousvc I didn't know you could do that.\"}, {'id': '1473022001375637505', 'text': '#fleeting https://t.co/RTVRqVCPPs'}, {'id': '1470452257023926273', 'text': \"@dsa 💪 go get 'em @dsa and team.\"}, {'id': '1466879070700933125', 'text': \"@pandemona Thanks for all you've done, Sara!💙\"}], 'meta': {'oldest_id': '1466879070700933125', 'newest_id': '1487110905234034695', 'result_count': 5, 'next_token': '7140dibdnow9c7btw3z3axx9gaws9vdv7u5zy8cdkomyd'}}\n",
      "Good user id\n",
      "{'data': [{'id': '1453339686752063491', 'text': 'トリマのスロットで5000マイル当たった！\\n招待コード【rMYt-Fb57】を使ってみんなも #トリマ を始めよう！\\nhttps://t.co/W0Y1ElK2BG\\n#移動するだけでマイルが貯まる #ポイ活 #節約 #Amazonギフト券 #Tポイント #dポイント'}, {'id': '1418165847332245504', 'text': '花火！？ https://t.co/cHcLZiLrEf'}, {'id': '1368551955098857474', 'text': 'RT @walk_coin: ＼ユーザー様還元✨2021/03/21(日)まで／\\n#WalkCoin Twitterシェアキャンペーン開催\\n #Amazonギフト券 1万円相当が抽選で100名様に当たる🎁\\n①@walk_coinをフォロー\\n②このツイートをRT\\n③フォームにアプ…'}, {'id': '1360049626045317122', 'text': '■毎月1万人に1万円が当たる！＃セゾンのお月玉 招待コードは「23638117」です。セゾンPortal\\u3000UC Portal＞お月玉招待システム画面で招待コードをご入力ください。▼お月玉招待システムについてhttps://t.co/6RFgIJxjPq▼カードをお持ちでないお客様（入会特典付）https://t.co/qmdOWcNvjg'}, {'id': '1333773062043443200', 'text': 'RT @PayPayOfficial: ＼祝！ホークス日本一キャンペーン開催✨／\\n#PayPay ボーナス10万円相当が抽選で20名様に当たる🎊\\nさらにもれなくホークス日本一限定きせかえもプレゼント⚾️\\n\\n〆切は12/1中\\n1.@PayPayOfficial をフォロー＆このツ…'}], 'meta': {'oldest_id': '1333773062043443200', 'newest_id': '1453339686752063491', 'result_count': 5, 'next_token': '7140dibdnow9c7btw3w29enregjh3c00882n21mgxq2i8'}}\n",
      "not good id\n",
      "{'errors': [{'value': '52862731', 'detail': 'Could not find user with id: [52862731].', 'title': 'Not Found Error', 'resource_type': 'user', 'parameter': 'id', 'resource_id': '52862731', 'type': 'https://api.twitter.com/2/problems/resource-not-found'}]}\n",
      "not good id\n",
      "{'errors': [{'value': '1836278736274492', 'detail': 'Could not find user with id: [1836278736274492].', 'title': 'Not Found Error', 'resource_type': 'user', 'parameter': 'id', 'resource_id': '1836278736274492', 'type': 'https://api.twitter.com/2/problems/resource-not-found'}]}\n",
      "not good id\n",
      "{'errors': [{'value': '068212578', 'detail': 'Could not find user with id: [068212578].', 'title': 'Not Found Error', 'resource_type': 'user', 'parameter': 'id', 'resource_id': '068212578', 'type': 'https://api.twitter.com/2/problems/resource-not-found'}]}\n",
      "not good id\n",
      "{'errors': [{'value': '06050922273', 'detail': 'Could not find user with id: [06050922273].', 'title': 'Not Found Error', 'resource_type': 'user', 'parameter': 'id', 'resource_id': '06050922273', 'type': 'https://api.twitter.com/2/problems/resource-not-found'}]}\n",
      "not good id\n",
      "{'errors': [{'value': '86077362081488', 'detail': 'Could not find user with id: [86077362081488].', 'title': 'Not Found Error', 'resource_type': 'user', 'parameter': 'id', 'resource_id': '86077362081488', 'type': 'https://api.twitter.com/2/problems/resource-not-found'}]}\n"
     ]
    },
    {
     "ename": "ConnectionError",
     "evalue": "HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/users/7499380917235/tweets?max_results=5 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f6db81cd9f0>: Failed to establish a new connection: [Errno -2] Name or service not known'))",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mgaierror\u001b[0m                                  Traceback (most recent call last)",
      "\u001b[0;32m/usr/lib/python3.10/site-packages/urllib3/connection.py\u001b[0m in \u001b[0;36m_new_conn\u001b[0;34m(self)\u001b[0m\n\u001b[1;32m    173\u001b[0m         \u001b[0;32mtry\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 174\u001b[0;31m             conn = connection.create_connection(\n\u001b[0m\u001b[1;32m    175\u001b[0m                 \u001b[0;34m(\u001b[0m\u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0m_dns_host\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mport\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mtimeout\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0;34m**\u001b[0m\u001b[0mextra_kw\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m/usr/lib/python3.10/site-packages/urllib3/util/connection.py\u001b[0m in \u001b[0;36mcreate_connection\u001b[0;34m(address, timeout, source_address, socket_options)\u001b[0m\n\u001b[1;32m     72\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m---> 73\u001b[0;31m     \u001b[0;32mfor\u001b[0m \u001b[0mres\u001b[0m \u001b[0;32min\u001b[0m \u001b[0msocket\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mgetaddrinfo\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mhost\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mport\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mfamily\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0msocket\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mSOCK_STREAM\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m     74\u001b[0m         \u001b[0maf\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0msocktype\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mproto\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mcanonname\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0msa\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mres\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m/usr/lib/python3.10/socket.py\u001b[0m in \u001b[0;36mgetaddrinfo\u001b[0;34m(host, port, family, type, proto, flags)\u001b[0m\n\u001b[1;32m    954\u001b[0m     \u001b[0maddrlist\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0;34m[\u001b[0m\u001b[0;34m]\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 955\u001b[0;31m     \u001b[0;32mfor\u001b[0m \u001b[0mres\u001b[0m \u001b[0;32min\u001b[0m \u001b[0m_socket\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mgetaddrinfo\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mhost\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mport\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mfamily\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mtype\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mproto\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mflags\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m    956\u001b[0m         \u001b[0maf\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0msocktype\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mproto\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mcanonname\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0msa\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mres\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;31mgaierror\u001b[0m: [Errno -2] Name or service not known",
      "\nDuring handling of the above exception, another exception occurred:\n",
      "\u001b[0;31mNewConnectionError\u001b[0m                        Traceback (most recent call last)",
      "\u001b[0;32m/usr/lib/python3.10/site-packages/urllib3/connectionpool.py\u001b[0m in \u001b[0;36murlopen\u001b[0;34m(self, method, url, body, headers, retries, redirect, assert_same_host, timeout, pool_timeout, release_conn, chunked, body_pos, **response_kw)\u001b[0m\n\u001b[1;32m    698\u001b[0m             \u001b[0;31m# Make the request on the httplib connection object.\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 699\u001b[0;31m             httplib_response = self._make_request(\n\u001b[0m\u001b[1;32m    700\u001b[0m                 \u001b[0mconn\u001b[0m\u001b[0;34m,\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m/usr/lib/python3.10/site-packages/urllib3/connectionpool.py\u001b[0m in \u001b[0;36m_make_request\u001b[0;34m(self, conn, method, url, timeout, chunked, **httplib_request_kw)\u001b[0m\n\u001b[1;32m    381\u001b[0m         \u001b[0;32mtry\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 382\u001b[0;31m             \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0m_validate_conn\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mconn\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m    383\u001b[0m         \u001b[0;32mexcept\u001b[0m \u001b[0;34m(\u001b[0m\u001b[0mSocketTimeout\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mBaseSSLError\u001b[0m\u001b[0;34m)\u001b[0m \u001b[0;32mas\u001b[0m \u001b[0me\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m/usr/lib/python3.10/site-packages/urllib3/connectionpool.py\u001b[0m in \u001b[0;36m_validate_conn\u001b[0;34m(self, conn)\u001b[0m\n\u001b[1;32m   1009\u001b[0m         \u001b[0;32mif\u001b[0m \u001b[0;32mnot\u001b[0m \u001b[0mgetattr\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mconn\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0;34m\"sock\"\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0;32mNone\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m:\u001b[0m  \u001b[0;31m# AppEngine might not have  `.sock`\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m-> 1010\u001b[0;31m             \u001b[0mconn\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mconnect\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m   1011\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m/usr/lib/python3.10/site-packages/urllib3/connection.py\u001b[0m in \u001b[0;36mconnect\u001b[0;34m(self)\u001b[0m\n\u001b[1;32m    357\u001b[0m         \u001b[0;31m# Add certificate verification\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 358\u001b[0;31m         \u001b[0mconn\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0m_new_conn\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m    359\u001b[0m         \u001b[0mhostname\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mhost\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m/usr/lib/python3.10/site-packages/urllib3/connection.py\u001b[0m in \u001b[0;36m_new_conn\u001b[0;34m(self)\u001b[0m\n\u001b[1;32m    185\u001b[0m         \u001b[0;32mexcept\u001b[0m \u001b[0mSocketError\u001b[0m \u001b[0;32mas\u001b[0m \u001b[0me\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 186\u001b[0;31m             raise NewConnectionError(\n\u001b[0m\u001b[1;32m    187\u001b[0m                 \u001b[0mself\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0;34m\"Failed to establish a new connection: %s\"\u001b[0m \u001b[0;34m%\u001b[0m \u001b[0me\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;31mNewConnectionError\u001b[0m: <urllib3.connection.HTTPSConnection object at 0x7f6db81cd9f0>: Failed to establish a new connection: [Errno -2] Name or service not known",
      "\nDuring handling of the above exception, another exception occurred:\n",
      "\u001b[0;31mMaxRetryError\u001b[0m                             Traceback (most recent call last)",
      "\u001b[0;32m/usr/lib/python3.10/site-packages/requests/adapters.py\u001b[0m in \u001b[0;36msend\u001b[0;34m(self, request, stream, timeout, verify, cert, proxies)\u001b[0m\n\u001b[1;32m    438\u001b[0m             \u001b[0;32mif\u001b[0m \u001b[0;32mnot\u001b[0m \u001b[0mchunked\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 439\u001b[0;31m                 resp = conn.urlopen(\n\u001b[0m\u001b[1;32m    440\u001b[0m                     \u001b[0mmethod\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0mrequest\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mmethod\u001b[0m\u001b[0;34m,\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m/usr/lib/python3.10/site-packages/urllib3/connectionpool.py\u001b[0m in \u001b[0;36murlopen\u001b[0;34m(self, method, url, body, headers, retries, redirect, assert_same_host, timeout, pool_timeout, release_conn, chunked, body_pos, **response_kw)\u001b[0m\n\u001b[1;32m    754\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 755\u001b[0;31m             retries = retries.increment(\n\u001b[0m\u001b[1;32m    756\u001b[0m                 \u001b[0mmethod\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0murl\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0merror\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0me\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0m_pool\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0mself\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0m_stacktrace\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0msys\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mexc_info\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m[\u001b[0m\u001b[0;36m2\u001b[0m\u001b[0;34m]\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m/usr/lib/python3.10/site-packages/urllib3/util/retry.py\u001b[0m in \u001b[0;36mincrement\u001b[0;34m(self, method, url, response, error, _pool, _stacktrace)\u001b[0m\n\u001b[1;32m    573\u001b[0m         \u001b[0;32mif\u001b[0m \u001b[0mnew_retry\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mis_exhausted\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 574\u001b[0;31m             \u001b[0;32mraise\u001b[0m \u001b[0mMaxRetryError\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0m_pool\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0murl\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0merror\u001b[0m \u001b[0;32mor\u001b[0m \u001b[0mResponseError\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mcause\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m    575\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;31mMaxRetryError\u001b[0m: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/users/7499380917235/tweets?max_results=5 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f6db81cd9f0>: Failed to establish a new connection: [Errno -2] Name or service not known'))",
      "\nDuring handling of the above exception, another exception occurred:\n",
      "\u001b[0;31mConnectionError\u001b[0m                           Traceback (most recent call last)",
      "\u001b[0;32m/tmp/ipykernel_8783/76417882.py\u001b[0m in \u001b[0;36m<module>\u001b[0;34m\u001b[0m\n\u001b[1;32m      2\u001b[0m \u001b[0;32mfor\u001b[0m \u001b[0mi\u001b[0m \u001b[0;32min\u001b[0m \u001b[0mrange\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;36m300\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m      3\u001b[0m         \u001b[0;31m# Get the timeline\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m----> 4\u001b[0;31m         \u001b[0mtimeline\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0muser_id\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mget_timeline\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;36m5\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m      5\u001b[0m         \u001b[0;31m# Add the timeline to the dictionary\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m      6\u001b[0m         \u001b[0musers_timeline\u001b[0m\u001b[0;34m[\u001b[0m\u001b[0muser_id\u001b[0m\u001b[0;34m]\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mtimeline\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m/tmp/ipykernel_8783/896546326.py\u001b[0m in \u001b[0;36mget_timeline\u001b[0;34m(num_tweets)\u001b[0m\n\u001b[1;32m     10\u001b[0m                         \u001b[0;34m'user-agent'\u001b[0m\u001b[0;34m:\u001b[0m \u001b[0;34m'v2FilteredStreamPython'\u001b[0m\u001b[0;34m,\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m     11\u001b[0m \t\t}\n\u001b[0;32m---> 12\u001b[0;31m                 \u001b[0mresponse\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mrequests\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mget\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0murl\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mheaders\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0mheaders\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mjson\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m     13\u001b[0m                 \u001b[0;32mtry\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m     14\u001b[0m                         \u001b[0;32mif\u001b[0m \u001b[0mlen\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mresponse\u001b[0m\u001b[0;34m[\u001b[0m\u001b[0;34m'data'\u001b[0m\u001b[0;34m]\u001b[0m\u001b[0;34m)\u001b[0m \u001b[0;34m==\u001b[0m \u001b[0mnum_tweets\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m/usr/lib/python3.10/site-packages/requests/api.py\u001b[0m in \u001b[0;36mget\u001b[0;34m(url, params, **kwargs)\u001b[0m\n\u001b[1;32m     73\u001b[0m     \"\"\"\n\u001b[1;32m     74\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m---> 75\u001b[0;31m     \u001b[0;32mreturn\u001b[0m \u001b[0mrequest\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m'get'\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0murl\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mparams\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0mparams\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0;34m**\u001b[0m\u001b[0mkwargs\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m     76\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m     77\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m/usr/lib/python3.10/site-packages/requests/api.py\u001b[0m in \u001b[0;36mrequest\u001b[0;34m(method, url, **kwargs)\u001b[0m\n\u001b[1;32m     59\u001b[0m     \u001b[0;31m# cases, and look like a memory leak in others.\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m     60\u001b[0m     \u001b[0;32mwith\u001b[0m \u001b[0msessions\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mSession\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m)\u001b[0m \u001b[0;32mas\u001b[0m \u001b[0msession\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m---> 61\u001b[0;31m         \u001b[0;32mreturn\u001b[0m \u001b[0msession\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mrequest\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mmethod\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0mmethod\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0murl\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0murl\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0;34m**\u001b[0m\u001b[0mkwargs\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m     62\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m     63\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m/usr/lib/python3.10/site-packages/requests/sessions.py\u001b[0m in \u001b[0;36mrequest\u001b[0;34m(self, method, url, params, data, headers, cookies, files, auth, timeout, allow_redirects, proxies, hooks, stream, verify, cert, json)\u001b[0m\n\u001b[1;32m    540\u001b[0m         }\n\u001b[1;32m    541\u001b[0m         \u001b[0msend_kwargs\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mupdate\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0msettings\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 542\u001b[0;31m         \u001b[0mresp\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0msend\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mprep\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0;34m**\u001b[0m\u001b[0msend_kwargs\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m    543\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    544\u001b[0m         \u001b[0;32mreturn\u001b[0m \u001b[0mresp\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m/usr/lib/python3.10/site-packages/requests/sessions.py\u001b[0m in \u001b[0;36msend\u001b[0;34m(self, request, **kwargs)\u001b[0m\n\u001b[1;32m    653\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    654\u001b[0m         \u001b[0;31m# Send the request\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 655\u001b[0;31m         \u001b[0mr\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0madapter\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0msend\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mrequest\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0;34m**\u001b[0m\u001b[0mkwargs\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m    656\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    657\u001b[0m         \u001b[0;31m# Total elapsed time of the request (approximately)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m/usr/lib/python3.10/site-packages/requests/adapters.py\u001b[0m in \u001b[0;36msend\u001b[0;34m(self, request, stream, timeout, verify, cert, proxies)\u001b[0m\n\u001b[1;32m    514\u001b[0m                 \u001b[0;32mraise\u001b[0m \u001b[0mSSLError\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0me\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mrequest\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0mrequest\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    515\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 516\u001b[0;31m             \u001b[0;32mraise\u001b[0m \u001b[0mConnectionError\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0me\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mrequest\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0mrequest\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m    517\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    518\u001b[0m         \u001b[0;32mexcept\u001b[0m \u001b[0mClosedPoolError\u001b[0m \u001b[0;32mas\u001b[0m \u001b[0me\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;31mConnectionError\u001b[0m: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/users/7499380917235/tweets?max_results=5 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f6db81cd9f0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
     ]
    }
   ],
   "source": [
    "users_timeline = {}\n",
    "for i in range(300):\n",
    "\t# Get the timeline \n",
    "\ttimeline, user_id = get_timeline(5)\n",
    "\t# Add the timeline to the dictionary\n",
    "\tusers_timeline[user_id] = timeline\n",
    "# Write the dictionary to a json file\n",
    "with open('../../data/300_random_users_first_5_tweets.json', 'w') as f:\n",
    "\tjson.dump(users_timeline, f)"
   ]
  }
 ],
 "metadata": {
  "interpreter": {
   "hash": "31f2aee4e71d21fbe5cf8b01ff0e069b9275f58929596ceb00d14d90e3e16cd6"
  },
  "kernelspec": {
   "display_name": "Python 3.7.3 64-bit",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.1"
  },
  "orig_nbformat": 4
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
